-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 20:01:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blueenergy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blueenergy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blueenergy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `blueenergy` ;

-- -----------------------------------------------------
-- Table `blueenergy`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueenergy`.`customer` (
  `customer_id` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blueenergy`.`meter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueenergy`.`meter` (
  `mpxn` DECIMAL(21,0) NOT NULL,
  `serial_number` DOUBLE NULL DEFAULT NULL,
  `meter_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`mpxn`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blueenergy`.`reading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueenergy`.`reading` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mpxn` DECIMAL(21,0) NULL DEFAULT NULL,
  `customer_id` VARCHAR(45) NULL DEFAULT NULL,
  `read_type` VARCHAR(45) NULL DEFAULT NULL,
  `register_id` INT(11) NULL DEFAULT NULL,
  `value` INT(11) NULL DEFAULT NULL,
  `read_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `mpxn_idx` (`mpxn` ASC) VISIBLE,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `blueenergy`.`customer` (`customer_id`),
  CONSTRAINT `mpxn`
    FOREIGN KEY (`mpxn`)
    REFERENCES `blueenergy`.`meter` (`mpxn`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
